//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class compte_rendu
    {
        public int ID { get; set; }
        public int ActivitesID { get; set; }
        public string Titre_cr { get; set; }
        public Nullable<System.DateTime> Date_debut { get; set; }
        public Nullable<System.DateTime> Date_fin { get; set; }
        public Nullable<int> Sujet1 { get; set; }
        public Nullable<int> Sujet2 { get; set; }
        public Nullable<int> Autre { get; set; }
        public Nullable<bool> Statut { get; set; }
    
        public virtual Activite Activite { get; set; }
    }
}
