
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MinisitreFin.Models
{

using System;
    using System.Collections.Generic;
    
public partial class compte_rendu
{

    public int ID { get; set; }

    public int ActivitesID { get; set; }

    public string Titre_cr { get; set; }

    public Nullable<System.DateTime> Date_debut { get; set; }

    public Nullable<System.DateTime> Date_fin { get; set; }

    public string Sujet1 { get; set; }

    public string Sujet2 { get; set; }

    public string Autre { get; set; }

    public Nullable<bool> Statut { get; set; }



    public virtual Activites Activites { get; set; }

}

}
