
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MinisitreFin.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Examens
{

    public int Id { get; set; }

    public Nullable<int> PatientId { get; set; }

    public string A { get; set; }

    public string A_Text { get; set; }

    public string B { get; set; }

    public string B_Text { get; set; }

    public string C { get; set; }

    public string C_Text { get; set; }

    public string D { get; set; }

    public string D_Text { get; set; }

    public string E { get; set; }

    public string E_Text { get; set; }

    public string F { get; set; }

    public string F_Text { get; set; }

    public string G { get; set; }

    public string G_Text { get; set; }

    public string H { get; set; }

    public string H_Text { get; set; }

    public string I { get; set; }

    public string I_Text { get; set; }

    public string J { get; set; }

    public string J_Text { get; set; }

    public string Statut { get; set; }

    public string ordonnance_ { get; set; }



    public virtual Patient Patient { get; set; }

}

}
