
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MinisitreFin.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Groupe_thematiqe
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Groupe_thematiqe()
    {

        this.Agenda = new HashSet<Agenda>();

        this.groue_detail = new HashSet<groue_detail>();

        this.Membre_group = new HashSet<Membre_group>();

    }


    public int ID { get; set; }

    public int CreatedById { get; set; }

    public string Nom_groupe { get; set; }

    public Nullable<System.DateTime> Date_createion { get; set; }

    public Nullable<bool> Statut { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Agenda> Agenda { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<groue_detail> groue_detail { get; set; }

    public virtual Utilisateur Utilisateur { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Membre_group> Membre_group { get; set; }

}

}
