
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MinisitreFin.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Membre_group
{

    public int Id { get; set; }

    public int GroupId { get; set; }

    public int MembreId { get; set; }



    public virtual Groupe_thematiqe Groupe_thematiqe { get; set; }

    public virtual Utilisateur Utilisateur { get; set; }

}

}
