
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MinisitreFin.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Programme
{

    public int ID { get; set; }

    public int UtilisateurID { get; set; }

    public string Nom_prog { get; set; }

    public string Objectif_prog { get; set; }

    public Nullable<System.DateTime> Date_debut { get; set; }

    public Nullable<System.DateTime> Date_fin { get; set; }

    public string Donateur { get; set; }

    public Nullable<double> budget { get; set; }



    public virtual Utilisateur Utilisateur { get; set; }

}

}
