
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MinisitreFin.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Projet
{

    public int ID { get; set; }

    public int ID_Initiative { get; set; }

    public string Nom_projet { get; set; }

    public string Description { get; set; }

    public string Objectif_projet { get; set; }

    public Nullable<System.DateTime> Date_debut { get; set; }

    public Nullable<System.DateTime> Date_fin { get; set; }



    public virtual Initiatives Initiatives { get; set; }

}

}
